import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./GlobalRedux/provider";
import NavBar from "./NavBar";
import MyApp from "../../pages/_app";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Yadav",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MyApp>
          <Providers>
            <NavBar></NavBar>
            {children}
          </Providers>
        </MyApp>
      </body>
    </html>
  );
}
